### ISSUE TITLE
[Inscription]: Deny capabilities for safe, fast actors

### ISSUE THREAD

**Issue by in-the-mood-for-mov** [belmarca/cla-ltp#1]
### Qui

Simon Génier

### Quand

20-01-2022

### Titre

Deny capabilities for safe, fast actors

### Citation

Sylvan Clebsch, Sophia Drossopoulou, Sebastian Blessing, and Andy McNeil. 2015. Deny capabilities for safe, fast actors. In Proceedings of the 5th International Workshop on Programming Based on Actors, Agents, and Decentralized Control (AGERE! 2015). Association for Computing Machinery, New York, NY, USA, 1–12. DOI:https://doi.org/10.1145/2824815.2824816

### PDF

https://dl.acm.org/doi/pdf/10.1145/2824815.2824816

**Comment by belmarca** [comment]
Inscrit, merci!
