### ISSUE TITLE
[Inscription]: A Small Scheme VM, Compiler, and REPL in 4K

### ISSUE THREAD

**Issue by laurenthuberdeau** [belmarca/cla-ltp#2]
### Qui

Laurent Huberdeau

### Quand

27-01-2022

### Titre

A Small Scheme VM, Compiler, and REPL in 4K

### Citation

Samuel Yvon and Marc Feeley. 2021. A small scheme VM, compiler, and REPL in 4k. In Proceedings of the 13th ACM SIGPLAN International Workshop on Virtual Machines and Intermediate Languages (VMIL 2021). Association for Computing Machinery, New York, NY, USA, 14–24. DOI:https://doi.org/10.1145/3486606.3486783    

### PDF

http://www.iro.umontreal.ca/~feeley/papers/YvonFeeleyVMIL21.pdf

**Comment by belmarca** [comment]
Merci!
